language: php

env:
  global:
    - 'FTP_USER=uasmitra'
    - 'FTP_PASS=mitra'

script:
  # script buat folder baru
  #- "curl -u $FTP_USER:$FTP_PASS fto://files.00webhost.com -Q 'mkd public_html'"

  # script upload file *.php
  - "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T input.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T simpandata.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T form-edit.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T update.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T hapus.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
  - "curl -T main.php -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/"
  - "curl -T proses.php -u $FTP_USER:$FTP_PASSWORD ftp://files.000webhost.com/public_html/"